# Change these first
owner: DagsHub # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: DagsHub
    url: https://dagshub.com/
  - name: Blog
    url: https://dagshub.com/blog/
  - name: Docs
    url: https://dagshub.com/docs/

status-website:
  baseUrl: /uptime
  logoUrl: https://github.com/DagsHub/client/blob/master/dagshub_github.png?raw=true
  name: Status
  introTitle: "Check the **DagsHub** website status"
#   introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
